sudo: required
language: groovy
services:
- docker
jdk:
- oraclejdk8
env:
  global:
  - secure: aYzChvsvf4inzWPicZn9+n35RdBW3ICx2LLlojJlZb5la0sjtnGLc1gwRsCj+WkvPAu7O855P7pwkTkRE1BixRacLjZf48vh1nw2cWf89330bQn35esbE0rLwOFvUx2w5liMO3/1AXzjhaFLJShJ+75L/q/qYN0iKtPHRIGIA1BgZDEZD5HKhpT5o6Iz787AJqF1kkl4IufVFo/xlFEz7KkpMlUObydSdGqQbyaSIZrFOvmEixnn/t7u944hfKdp+gvT1fXfRFunqIlQO/5elYeSz1pueIf6pROnW3n2xurTDx4OeT/AWusZWZ1sINT3v9R6uhkIC0ry149vOWxI1V57Lbkitw9fIb62FvIT9I+ucoqWTJVqMqCyL4/AIBOXqTFJbkTguW6eRJrQyigLVAQjVUMdFS13AQsJwju5r8P0dm0YubzNBi2NMnwjoHzZ79DiAxmJ5ksfQ3bhMISETd+dbJFa3qYKsh1FZdkGC1sdZ1R7hD7qKqQyi/Qw2jL7CSNeH8XAyo4a7i/IKIntVy3ZTRYlf7/S4KPnanHgG3uIM/QaW/2f30dmhyBtvKSekRfIXWfHbjNB1T6SY2AISZaGEteC0DI7m8XspXiMbdRGoqqb4zudcX9TUdh0KxGY6+vHEkShrUt2J7PtvzMo1IqJEZC50hJKNV/Tle/w4Ug=
  - secure: LX7CjqzkFQgP5NV1CUCGtcPBTqKlm1eSIytylHye8ajPxqzQtpLe2tNo+lYwUWdHIyHjKEn18MbnOKEH46zOf9gk2Ptb2zDAVQQYvAISNVjBMNhlXPtzClSPaZimJzxf2Tf80QoHzJbZDSm22ZKqXcz8kXjHvuT4V2AN2M9IlQidAZwGUNeuWY4uTa/gPRzq/AUSjy7Y0WNGjlTwOf0FZcCHbqKMD+HqNSHzW93e/ZwGMDP1Sq49Uw0WB62QtxKnxodXGpCv/aFU5uVmhO8Dre89WpLDX70KJNnx4LGmOYJm5wkpV6N4l7+tdOca1WQtSyOXfizGgTCOvuMHXr7Stsiu9+hVyzo3pHMMX++PbhSRjNJsUSBlqcNREtk/CKl8+2OxSTu9Y7tJiG9ZKo1Pw11ytSGZzNSPy0yUdoVbsj7gicmB3LXjL1YgZZtwaoEq9IzjPA4axkcNFD5ZlWcAuwP9+baqRLp1TCBXMLNAXHxUFYaGjiJjW7mRUzwEfRjwdlzo3aDSD4Yw/tefIPB0+t0lZ4CyjsiiIIYW2Yz75fzGL8MO0at7+vFCqHknFe/omdjxpmF0BxjiYQlY/j8mbZR4Ij1C+mAXkMmy5doQXw0AF/0heykiBlrJqzxET+RCvxj7BnOowxfDP7CdcsSjRXHIERYir06d0ajf2NG8oss=
branches:
  only:
  - master
script:
- ./gradlew check
- ./gradlew assemble
- docker build -t $DOCKER_USER/config-server .
- docker tag $DOCKER_USER/config-server $DOCKER_USER/config-server:latest
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push $DOCKER_USER/config-server
notifications:
  email:
    on_failure: change
    on_success: change
