sudo: required
language: groovy
services:
- docker
jdk:
- oraclejdk8
env:
  global:
  - secure: aYzChvsvf4inzWPicZn9+n35RdBW3ICx2LLlojJlZb5la0sjtnGLc1gwRsCj+WkvPAu7O855P7pwkTkRE1BixRacLjZf48vh1nw2cWf89330bQn35esbE0rLwOFvUx2w5liMO3/1AXzjhaFLJShJ+75L/q/qYN0iKtPHRIGIA1BgZDEZD5HKhpT5o6Iz787AJqF1kkl4IufVFo/xlFEz7KkpMlUObydSdGqQbyaSIZrFOvmEixnn/t7u944hfKdp+gvT1fXfRFunqIlQO/5elYeSz1pueIf6pROnW3n2xurTDx4OeT/AWusZWZ1sINT3v9R6uhkIC0ry149vOWxI1V57Lbkitw9fIb62FvIT9I+ucoqWTJVqMqCyL4/AIBOXqTFJbkTguW6eRJrQyigLVAQjVUMdFS13AQsJwju5r8P0dm0YubzNBi2NMnwjoHzZ79DiAxmJ5ksfQ3bhMISETd+dbJFa3qYKsh1FZdkGC1sdZ1R7hD7qKqQyi/Qw2jL7CSNeH8XAyo4a7i/IKIntVy3ZTRYlf7/S4KPnanHgG3uIM/QaW/2f30dmhyBtvKSekRfIXWfHbjNB1T6SY2AISZaGEteC0DI7m8XspXiMbdRGoqqb4zudcX9TUdh0KxGY6+vHEkShrUt2J7PtvzMo1IqJEZC50hJKNV/Tle/w4Ug=
  - secure: jfYgJ5MY130NRNuJi5LVPHWq77v+lPmxbI7Cb1AFSOYAW4CH9tn5CQnmIKrsWPAHpR5kG/bKs8XEyBAx+kyusB9+QDh8ARVqMs3VneklpQs+FNZEcZuXcAdjmfMnJejHLeABktW+32YYdiTeUkDra+SsYSQ3AMeHwIEuPNm1bKZubWDWgma3WjXnCmUfVfwXVdtiv9Uou/HsbqUbvsftrwXhh4y3gp731R+vC9x7w1ujxE+dNMqs+b1d8rLJjKjqSzsA/PKh1ibbgoltr8koJsY7PO/9A14TLAvHtasHmPxo5a2r58WILC1jBVmkROmveYui7ymjPYcLmj1Q0+ErbrTy8C4XsyOavd29UUA8rS7p6Y7j9Xud2c1ADACCB6SNwfLkejw0TxLZldpO/DyC3b4rQcJEYmUgwiB74wGf6oQVVhjO44m64HZ2l6T24h6z9p2J2FBWlY2XMm6sPIEInzU4kKz1qoqq4zVdR76Bdu6rqcuHghV0ZW1JOmPBeS82fRcPszhE/NzdHFI2OvhC/XB0dPPVQUFAGFVC9Jb0JRbWfu61IzuyQgEsdpjxJ69M1zeN77xOmRiMOL0yizj1ypcVMMJDm1NmG0EGCzhsIZ7qPmdkTzCmjCD65TVaG9qGVBFYTdpWMqdJwG81n/apnLibssHnyrp+KAaPgeSLrv4=
branches:
  only:
  - master
script:
- ./gradlew check
- ./gradlew assemble
- docker build -t $DOCKER_USER/config-server .
- docker tag $DOCKER_USER/config-server $DOCKER_USER/config-server:latest
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push $DOCKER_USER/config-server
notifications:
  email:
    on_failure: change
    on_success: change
