sudo: required
language: groovy
services:
- docker
jdk:
- oraclejdk8
env:
  global:
  - secure: jGZ2e8k0we4k28GfWjSp0BbLkxq2rBih8HIPuqdaQiW9h54Bul/dZImVkUjOORbL8tv8nyKan2EGDTAYkg4vdPL+EFAyLJW5Py7e7CZGHACJCL1CpNvYQrGKc2Pu52/ELWiC5JihV134lhtDQl3yaoYtbxUyackv8tL6G8OYnvI/bnLSJr7mRra9Idnbx+Vzgs3KTkDFS9KIDQGUl2+N7IWg62BVnzEEFngjnltag8MlkZ2GJZATs5poK10m9bZWZCQgmsTJRxL8CUQAtz0evHnLyyNqeKFgtDorlvvYlLxBmY6NfjX7oLiyfnnMkelP1y99WgglNdCNkfi1gPsrrAt3RAnvP3C1Lvv9qoObDgcL89hL+hOHjX5a8+ujGyveCO8k/PHapY7hgcKuH5TDpcRp2/Ca5IDHcbFoBSFEgM1mII/1jecG9lAh+eNmEw9X61tuwIbXqN8k7Ddtsk6uEPwsRZkinnGFIMC/C9lBSUn6p7FAcaypqK5KdzkcdcCKSwB+kXEmfu7ws+GFwRB81S3RErT0SDmpAZ2lhJCyMKCFEOYTRYyejs+cIyuWRZ7uGaMJrQ1kelSL7r4g0nSZ2mtxsXKPMZ5PfUZ6zT2RGAO3vDmYSL7uFbe5L8V8jKIsPfc0LFfbR1OkR+AknHES3I8WTXmzAS4fzGivbhKRAyU=
  - secure: ovtvv+qLIzjWU3fwZygmFWhh3FqsIUuXqSfvte7as05uVzbhIkSdS02HckHZs88H8nEXLZhVRhoPw7IsLuCFZAicBd+EDEInHhqfo/ihwydWYcK3xTiOFWZy5cSDFvJ3OHyFEwc3DR2ztmdfNOXy42CTZk6RWfahy7GXmdTcgaIK6QA8GZIohrnEPq+udRSrMJG312oRPu22Q4HTi9SMCvANnlBe1OnheLQi72oUu49hAI8ZsGI7df/GMp+AhxhQoYZq8I86+SRrg9yuXgF7lARkfcNDlYolQKuvixAOnk5ErQ/Ck01WWoLNUHGhXfYsMjfPyMYaeC8p4IFnOFAQnz9cRmcd4jTzHlgFmCkMPg5daWdcegcJP8NuCQowFX4T2iWyHoY99MtKR6uETLeT3v9WVTks4ak19ozHJlYFOKxpOks/q46BLxeR0hyQuK35Etu6vBiS/JoE7RTn8DRV+0WvW6qRDEVn8UbEIqpqs5gFYFtrbtNEeG/soO9lByXcdD3ZWLXcMcHwS9Mg3scKDh7J+sb6efi8jeMfO1IlniNiMKld+tN7xx4/zdZu9d4QDTTn2FX5ueO7Lq3Kh9BeEb3X+RzmBFXe1JuU5LPKxNXS6r/IinVncY15K+SiC98yZJKwyZBL9iMBgYyyZHybm20ybwvaLJWZ8uDe8fJ+jag=
branches:
  only:
  - master
script:
- ./gradlew check
- ./gradlew assemble
- docker build -t $DOCKER_USER/config-server .
- docker tag $DOCKER_USER/config-server $DOCKER_USER/config-server:latest
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push $DOCKER_USER/config-server
notifications:
  email:
    on_failure: change
    on_success: change
